application: dectoroman
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.+\.php)$
  script: \1
  
- url: /static
  static_dir: static
  
- url: /images
  static_dir: images
  
- url: /.*
  script: index.php